name: Test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: my-action
        uses: ./.github/actions/my-action/
        with:
          message: "Henry"
