name: Ejemplo de Composite Actions

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    env:
      MY_VAR: Mi variable de entorno

    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_ROOT_PASSWORD: example
    #     ports:
    #       - 3306:3306
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379

    steps:
      - name: Variables
        env:
          MY_VAR_STEP: Mi variable dentro del step
        run: |
          echo "Valor $MY_VAR"
          echo "Valor $MY_VAR_STEP"
          echo "Valor ${{ vars.MY_GLOBAL_VAR }}"

      - name: Secrets
        run: |
          echo "Valor ${{ secrets.MY_SQL_PASSWORD }}"
