---
name: Hola Mundo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
      - name: Create file
        run: touch hola.txt
      - name: Append text
        run: echo "using GHA" >> hola.txt
      - name: Read file
        run: cat hola.txt
  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: LS
        run: ls -al
